### PR TITLE
target_family is now optional

### LINKED ISSUE #9: Modern git-master doesn't work with rustc-cfg
Commit c59bb4979c6d2e994b01d6ed9e005f8881a36935 in the rust compiler means that rustc-cfg panics because targets such as thumbv6m-none-eabi lack a family (not unix, not windows) but rustc-cfg expects there to always be a family etc.

### PR DESCRIPTION
**Pull request by japaric**
closes #9

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c42d524 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c42d524 with merge c42d524...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/187630562)
Approved by: japaric
Pushing c42d524aee1ed4c4b1e0a14ec39ded06c7d7e8e6 to master...

**Pull request merged**
