### PR TITLE
Cfg::new: prefer RUSTC over rustc

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e61f99f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e61f99f with merge 9ca7562...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/159996345)
Approved by: japaric
Pushing 9ca7562bd9dd72ac2fab6441741983ea32b0fb91 to master...

**Pull request merged**
