### PR TITLE
Cfg::new now returns Result<Cfg, String>

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5e1204c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5e1204c with merge 5e1204c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/164522359)
Approved by: japaric
Pushing 5e1204cad4e1a6fef2cf78147c105c08a0ab2f56 to master...

**Pull request merged**
