### PR TITLE
.travis: remove webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0898e2e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0898e2e with merge 0898e2e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/174111800)
Approved by: japaric
Pushing 0898e2e2e76879e6df99fae16e660113f3252545 to master...

**Pull request merged**
