### PR TITLE
parse target_vendor

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d64fa78 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d64fa78 with merge d64fa78...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/160293823)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 80a4747 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 80a4747 with merge 80a4747...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/160302598)
Approved by: japaric
Pushing 80a474764f7147c0aa107391063563706ce3f842 to master...

**Pull request merged**
