### PR TITLE
homu-ify

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 637afcd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 637afcd with merge 637afcd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/rustc-cfg/builds/159995962)
Approved by: japaric
Pushing 637afcddd8d2666adc12455bff1ef823a9675268 to master...

**Pull request merged**
